### ISSUE TITLE
Bug in con_cordis() function related normalizePath - unnamed parameter value intended mustWork

### ISSUE THREAD

**Issue by mskyttner** [KTH-Library/cordis#3]

**Comment by mohabazzi** [comment]
Parquet files are in C:\Users\moham\AppData\Local\cordis\cordis\Cache\temp, populating database ...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': rapi_startup: Failed to open database: IO Error: Cannot open file "C:\Users\moham\AppData\Local\cordis\cordis\Cache\cordisdb": The process cannot access the file because it is being used by another process.

**Comment by mohabazzi** [comment]
Update: 

Kolande ned repot igen och la samtliga filer i ny mapp i C. Koppling mot git ser ut att funka vid öppnadet av R projekt filen. Likaså funkar det att hämta ned alla parquet filer genom 'cordis_import(refresh = T)' utan någon tjafs. Vad jag gjorde var att lägga till dina förändringar av både cordis_con and cordis_import som sparas som nya funktioner i min R miljö. Efter detta slutar allt annat funka och då får jag en serie olika felmeddelanden beroende på vad jag försöker göra.

**Comment by mskyttner** [comment]
- Fungerar anropen cordis_import(refresh = T)? Du skriver att det gör det, dvs inga felmeddelanden?
- Du behöver ladda och bygga paketet (Ctrl-Shift-L resp Ctrl-Shift-B) och behöver därefter inte skriva över funktioner i din aktiva miljö (environment). Vill du göra testa ändringar så gör du detta i filer i R-biblioteket och laddar om paketet (ctrl-shift-d, ctrl-shift-l, ctrl-shift-b). Dvs att lägga till förändringar som sparas i ditt workspace i nya funktioner bör väl undvikas?
- Jag tror att det är två separata issues här, där eventuellt den andra "error in evaluating "drv" är den som jag inte lyckas återskapa
- Jag behöver ett sätt att reproducera det problemet. Kan du beskriva stegen du gör exakt? När jag provar att installera branchen och köra i en container så verkar det fungera:

```r
# run this R script in RStudio with kthcorpus installed using this docker invocation:
# NB: on win this probably needs some adjustments (?) for picking up the uid:gid stuff
#
# docker run -d --name kthcorpus --env ROOT=true --env USER=rstudio --env PASSWORD=kontarion --env USERID=$(id -u) --env GROUPID=$(id -g) --volume $(pwd):/home/rstudio --publish 8787:8787 ghcr.io/kth-library/kthcorpus /init
#
# log in to RStudio web UI at http://localhost:8787 with credentials above

# remove and reinstall in case older versions of packages are available
remove.packages(c("cordis", "duckdb"))
install.packages("duckdb")

# install the cordis package from a specific branch
library(devtools)
devtools::install_github("kth-library/cordis", ref = "fix-normalize-path")


library(dplyr)
library(cordis)

# get fresh data
cordis_import(refresh = TRUE)

# list tables and fields
cordis_tables()
cordis_schema()

# show countries table
con <- cordis_con()
con |> tbl("countries")
duckdb::dbDisconnect(con, shutdown = TRUE)

```

**Comment by mohabazzi** [comment]
Hej Markus,

Vill du ta ett snabbt zoom möte?

Hälsar,
Mohamad
________________________________

**Comment by mskyttner** [comment]
Sitter i föreläsningar samt seminarie med presentationer, så jag kan inte zooma, och ska nu snart åka på studiebesök, men försöker ha koll på mail/slack/github.

**Comment by mohabazzi** [comment]
Juste 🙂 No worries!

________________________________

**Comment by mohabazzi** [comment]
Hej Markus,

1. Började med att klona ned cordis repot i en nyskapad mapp i C enheten. 
2. Öppnar upp R projeketet. Git fliken är synlig. 
3. Kör följande funktioner: devtools::load_all()  --> devtools::build()
4. cordis_import(refresh = TRUE) # Works fine.
5. con <- cordis_con() # Works fine.
6. Con objektet ser ut på följande sätt

<duckdb_connection 961c0 driver=<duckdb_driver 52550 dbdir='C:\Users\moham\AppData\Local\cordis\cordis\Cache\cordisdb' read_only=FALSE bigint=numeric>>

7. Testar sedan följande: cordis_tables() och cordis_schema(), och får följande felmeddelande.

Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': rapi_startup: Failed to open database: IO Error: Cannot open file "C:\Users\moham\AppData\Local\cordis\cordis\Cache\cordisdb": The process cannot access the file because it is being used by another process.

8. Har kollar under details i task manager om filen cordisdb körs på annat håll, men det ser inte ut som det.

**Comment by mskyttner** [comment]
Bra med steg-för-steg-beskrivning. Några saker att undersöka:

- om du stänger förbindelsen med `duckdb::dbDisconnect(con, shutdown=TRUE)`, misslyckas de där funktionsanropen även efter detta? För att förstå om det är den förbindelse du redan har öppnat mot databasen som står för "den andra processen".
- sökvägen är annorlunda än den jag har: dels är cordis-biblioteket dubblerat dvs ...\Local\cordis\cordis... finns filen cordisdb på detta ställe i ditt filsystem? Sedan vet jag inte om sökvägen behöver "winslash", dvs dubblerade backslash-tecken, men det kanske redan är så (bara att detta inte visas i felmeddelandet, vilket isåfall innebär att man behöver plocka ut strängen ur connection-objektet och titta på den för att förstå detta bättre)?
- kan [detta](https://serverfault.com/questions/1966/how-do-you-find-what-process-is-holding-a-file-open-in-windows) användas på Windows för att se vilken process som använder filen?

**Comment by mohabazzi** [comment]
Hej Markus,

Märkligt nog så har jag fått det att funka nu. Oklart vad som triggade felmeddelandet

Hälsar,
Mohamad
________________________________
